# Generated by Django 3.2.3 on 2021-05-17 05:46

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='detail',
            old_name='main',
            new_name='user',
        ),
    ]
